version: "3.8"
services:
  web:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    # Let the init system handle signals for us.
    # among other things this helps shutdown be fast
    init: true
    env_file:
      - infra/config/local_dev.env
