[tool.poetry]
name = "jira-bugzilla-integration"
version = "0"
description = "jira-bugzilla-integration"
authors = ["@mozilla/jbi-core"]
license = "MPL"

[tool.poetry.dependencies]
python = ">=3.10 <3.12"
fastapi = "^0.91.0"
pydantic = {version = "^1.10.4", extras = ["dotenv", "email"]}
uvicorn = {extras = ["standard"], version = "^0.20.0"}
atlassian-python-api = "^3.32.2"
dockerflow = "2022.8.0"
Jinja2 = "^3.1.2"
pydantic-yaml = {extras = ["pyyaml","ruamel"], version = "^0.9.0"}
sentry-sdk = {extras = ["fastapi"], version = "^1.15.0"}
backoff = "^2.2.1"
statsd = "^4.0.1"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.21.0"
black = "^23.1.0"
isort = "^5.12.0"
coverage = {extras = ["toml"], version = "^7.1"}
mypy = "^0.991"
detect-secrets = "^1.4.0"
bandit = "^1.7.0"
pylint = "^2.16.1"
pylint-pytest = "^1.1.2"
pytest = "^7.2.1"
yamllint = "^1.29.0"
pytest-dotenv = "^0.5.2"
types-requests = "^2.28.11"
responses = "^0.22.0"
httpx = "^0.23.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests/unit",
]
env_override_existing_values = true
env_files = [
    ".env.example"
]
markers = [
    "no_mocked_bugzilla",
    "no_mocked_jira",
]

[tool.pylint]
    [tool.pylint.'MESSAGES CONTROL']
    disable = [
        "C0301", #line-too-long
        "R0903", #too-few-public-methods
        "W0613", #unused-argument
    ]
    [tool.pylint.REPORTS]
    output-format = 'colorized'
    [tool.pylint.MASTER]
    load-plugins='pylint_pytest'
    ignore='third_party'
    ignore-patterns = "tests/*"
    extension-pkg-whitelist = "pydantic"
    [tool.pylint.SIMILARITIES]
    ignore-signatures = "yes"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
# Warn when returning Any from function with non-Any return
warn_return_any = true

[[tool.mypy.overrides]]
module = ["ruamel", "bugzilla", "atlassian", "statsd.defaults.env"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "jbi.app"
]
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
strict_concatenate = true

[tool.coverage]
# https://github.com/nedbat/coveragepy
    [tool.coverage.run]
    omit = [
        '*/.local/*',
        '/usr/*',
        '*/.venv/*',
        '*/.tox/*',
        '*/virtualenvs/*',
    ]

    [tool.coverage.report]

    exclude_lines = [
        "# noqa",
        "raise NotImplementedError",
        "pragma: no cover",
        "def __repr__",
        "if .debug:",
        "raise NotImplementedError",
        "if __name__ == .__main__.:",
        "logger.",
        "from",
        "import"
    ]
