[tool.poetry]
name = "jira-bugzilla-integration"
version = "0"
description = "jira-bugzilla-integration"
authors = ["@mozilla/jbi-core"]
license = "MPL"

[tool.poetry.dependencies]
python = ">=3.12, <3.13"
fastapi = "^0.110.0"
pydantic = {version = "^2.6.4", extras = ["email"]}
uvicorn = {extras = ["standard"], version = "^0.28.0"}
atlassian-python-api = "^3.41.11"
dockerflow = {extras = ["fastapi"], version = "2024.3.0"}
Jinja2 = "^3.1.3"
sentry-sdk = {extras = ["fastapi"], version = "^1.42.0"}
pydantic-yaml = "^1.2.1"
backoff = "^2.2.1"
statsd = "^4.0.1"
requests = "^2.31.0"
pydantic-settings = "^2.2.1"
pypandoc = "^1.13"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.2"
coverage = {extras = ["toml"], version = "^7.4"}
mypy = "^1.9"
detect-secrets = "^1.4.0"
bandit = "^1.7.8"
pytest = "^8.1.1"
yamllint = "^1.35.1"
pytest-dotenv = "^0.5.2"
types-requests = "^2.31.0"
responses = "^0.25.0"
httpx = "^0.27.0"
factory-boy = "^3.3.0"
pytest-factoryboy = "^2.7.0"
ruff = "^0.3.3"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
lint.extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
testpaths = [
    "tests/unit",
]
env_override_existing_values = true
env_files = [
    ".env.example"
]
markers = [
    "no_mocked_bugzilla",
    "no_mocked_jira",
]

[tool.mypy]
python_version = "3.12"
# Warn when returning Any from function with non-Any return
warn_return_any = true
plugins = "pydantic.mypy"

[[tool.mypy.overrides]]
module = ["ruamel", "bugzilla", "atlassian", "atlassian.rest_client", "statsd.defaults.env", "dockerflow.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "jbi.app"
]
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
strict_concatenate = true

[tool.coverage]
# https://github.com/nedbat/coveragepy
    [tool.coverage.run]
    omit = [
        '*/.local/*',
        '/usr/*',
        '*/.venv/*',
        '*/.tox/*',
        '*/virtualenvs/*',
    ]

    [tool.coverage.report]

    exclude_lines = [
        "# noqa",
        "raise NotImplementedError",
        "pragma: no cover",
        "def __repr__",
        "if .debug:",
        "raise NotImplementedError",
        "if __name__ == .__main__.:",
        "logger.",
        "from",
        "import"
    ]
