---
# Action Config
- whiteboard_tag: nonprodtest
  bugzilla_user_id: 644672
  description: Nonprod testing whiteboard tag (JBI Bin Project)
  parameters:
    jira_project_key: JB
    labels_brackets: both
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - maybe_update_components
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
        - sync_whiteboard_labels
        - sync_keywords_labels
      existing:
        - update_issue_summary
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
        - sync_whiteboard_labels
        - sync_keywords_labels
      comment:
        - create_comment

- whiteboard_tag: fxcm
  bugzilla_user_id: tbd
  description: Firefox Credential Management Team whiteboard tag
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_priority
        - maybe_update_issue_resolution
        - maybe_update_issue_severity
        - maybe_update_issue_status
        - sync_whiteboard_labels
      existing:
        - update_issue_summary
        - maybe_assign_jira_user
        - maybe_update_issue_priority
        - maybe_update_issue_resolution
        - maybe_update_issue_severity
        - maybe_update_issue_status
        - sync_whiteboard_labels
    labels_brackets: both
    status_map:
      ASSIGNED: To Do
      REOPENED: To Do
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: fxdroid
  bugzilla_user_id: 430528
  description: Firefox Android Team Tag
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_status
        - sync_whiteboard_labels
      existing:
        - update_issue_summary
        - maybe_assign_jira_user
        - maybe_update_issue_status
        - sync_whiteboard_labels
    labels_brackets: both
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Closed
      VERIFIED: Closed
      FIXED: Closed
      INVALID: Closed
      WONTFIX: Closed
      INACTIVE: Closed
      DUPLICATE: Closed
      WORKSFORME: Closed
      INCOMPLETE: Closed
      MOVED: Closed

- whiteboard_tag: fxp
  bugzilla_user_id: 396948
  description: Performance Team
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_components
        - maybe_update_issue_resolution
        - maybe_update_issue_status
        - sync_whiteboard_labels
        - sync_keywords_labels
      existing:
        - update_issue_summary
        - maybe_assign_jira_user
        - maybe_update_components
        - maybe_update_issue_resolution
        - maybe_update_issue_status
        - sync_whiteboard_labels
        - sync_keywords_labels
      comment:
        - create_comment
    labels_brackets: both
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: sp3
  bugzilla_user_id: 396948
  description: Speedometer 3
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_components
        - maybe_update_issue_resolution
        - maybe_update_issue_status
        - sync_whiteboard_labels
        - sync_keywords_labels
      existing:
        - update_issue_summary
        - maybe_assign_jira_user
        - maybe_update_components
        - maybe_update_issue_resolution
        - maybe_update_issue_status
        - sync_whiteboard_labels
        - sync_keywords_labels
      comment:
        - create_comment
    labels_brackets: both
    status_map:
      UNCONFIRMED: To Do
      NEW: To Do
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: dataplatform
  bugzilla_user_id: tbd
  description: Data Platform Infrastructure
  parameters:
    jira_project_key: JB
    jira_components:
      set_custom_components:
        - "Data Platform Infrastructure"
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - maybe_update_components
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue_summary
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      comment:
        - create_comment
    labels_brackets: both
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: dataquality
  bugzilla_user_id: tbd
  description: Data Quality
  parameters:
    jira_project_key: JB
    jira_components:
      set_custom_components:
        - "Data Quality"
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - maybe_update_components
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue_summary
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      comment:
        - create_comment
    labels_brackets: both
    status_map:
      UNCONFIRMED: To Do
      NEW: To Do
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done
