---
# Action Config
- whiteboard_tag: nonprodtest
  contact: 644672
  description: Nonprod testing whiteboard tag (JBI Bin Project)
  parameters:
    jira_project_key: JB

- whiteboard_tag: flowstate
  allow_private: true
  contact: 91159
  description: Flowstate whiteboard tag
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    status_map:
      ASSIGNED: In Progress
      FIXED: In Review
      REOPENED: In Progress

- whiteboard_tag: fxcm
  contact: tbd
  description: Firefox Credential Management Team whiteboard tag
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    status_map:
      ASSIGNED: To Do
      REOPENED: To Do
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: fxdroid
  contact: 430528
  description: Firefox Android Team Tag
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_status
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Closed
      VERIFIED: Closed
      FIXED: Closed
      INVALID: Closed
      WONTFIX: Closed
      INACTIVE: Closed
      DUPLICATE: Closed
      WORKSFORME: Closed
      INCOMPLETE: Closed
      MOVED: Closed

- whiteboard_tag: fxp
  contact: tbd
  description: Performance Team
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      comment:
        - create_comment
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: sp3
  contact: 396948
  description: Speedometer 3
  parameters:
    jira_project_key: JB
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      comment:
        - create_comment
    status_map:
      UNCONFIRMED: To Do
      NEW: To Do
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done
