---

# Action Config
actions:
  addons:
    #  action: src.jbi.whiteboard_actions.default
    contact: tbd
    description: Addons whiteboard tag for AMO Team
    enabled: true
    parameters:
      jira_project_key: WEBEXT
      whiteboard_tag: addons
  fidedi:
    contact: tbd
    description: Firefox Desktop Integration whiteboard tag
    enabled: true
    parameters:
      jira_project_key: FIDEDI
      whiteboard_tag: fidedi
  fidefe:
    contact: tbd
    description: Firefox Front End whiteboard tag
    enabled: true
    parameters:
      jira_project_key: FIDEFE
      whiteboard_tag: fidefe
  flowstate:
    contact: dtownsend@mozilla.com
    description: Flowstate whiteboard tag
    enabled: true
    allow_private: true
    parameters:
      jira_project_key: MR2
      whiteboard_tag: flowstate
  fxatps:
    contact: tbd
    description: Privacy & Security and Anti-Tracking Team whiteboard tag
    enabled: true
    parameters:
      jira_project_key: FXATPS
      whiteboard_tag: fxatps
  fxcm:
    contact: tbd
    description: Firefox Credential Management Team whiteboard tag
    enabled: true
    parameters:
      jira_project_key: FXCM
      whiteboard_tag: fxcm
  fxsync:
    contact: tbd
    description: Firefox Sync Team whiteboard tag
    enabled: true
    parameters:
      jira_project_key: SYNC
      whiteboard_tag: fxsync
  gv:
    contact: tbd
    description: GeckoView Team whiteboard tag
    enabled: true
    parameters:
      jira_project_key: ANDP
      whiteboard_tag: gv
  mv3:
    contact: tbd
    description: MV3 whiteboard tag
    enabled: true
    parameters:
      jira_project_key: WEBEXT
      whiteboard_tag: mv3
  nimbus:
    contact: tbd
    description: Nimbus whiteboard tag
    enabled: true
    parameters:
      jira_project_key: EXP
      whiteboard_tag: nimbus
  prodtest:
    contact: tbd
    description: ProdTest tag
    enabled: true
    parameters:
      jira_project_key: OSS
      whiteboard_tag: prodtest
  proton:
    contact: tbd
    description: Proton whiteboard tag for Firefox Frontend
    enabled: true
    parameters:
      jira_project_key: FIDEFE
      whiteboard_tag: proton
  relops:
    contact: tbd
    description: Release Operations Team Tag
    enabled: true
    parameters:
      jira_project_key: RELOPS
      whiteboard_tag: relops
  snt:
    contact: tbd
    description: Search/NewTab Team Tag
    enabled: true
    parameters:
      jira_project_key: SNT
      whiteboard_tag: snt
