---
# Action Config
- whiteboard_tag: jst
  contact: bsieber@mozilla.com
  description: What does JST mean?
  enabled: true
  parameters:
    jira_project_key: JST

- whiteboard_tag: flowstate
  allow_private: true
  contact: dtownsend@mozilla.com
  description: Flowstate whiteboard tag
  enabled: true
  module: src.jbi.whiteboard_actions.default_with_assignee_and_status
  parameters:
    jira_project_key: MR2
    status_map:
      ASSIGNED: In Progress
      FIXED: In Review
      REOPENED: In Progress
