---
# Action Config
- whiteboard_tag: addons
  contact: tbd
  description: Addons whiteboard tag for AMO Team
  # module: jbi.actions.default
  parameters:
    jira_project_key: WEBEXT

- whiteboard_tag: fidedi
  contact: tbd
  description: Firefox Desktop Integration whiteboard tag
  parameters:
    jira_project_key: FIDEDI

- whiteboard_tag: fidefe
  contact: 159069
  description: Firefox Front End whiteboard tag
  parameters:
    jira_project_key: FIDEFE
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    status_map:
      ASSIGNED: In Progress
      FIXED: Closed
      WONTFIX: Closed
      DUPLICATE: Closed
      INVALID: Closed
      INCOMPLETE: Closed
      WORKSFORME: Closed
      REOPENED: In Progress

- whiteboard_tag: flowstate
  contact: 91159
  description: Flowstate whiteboard tag
  parameters:
    jira_project_key: MR2
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    sync_whiteboard_labels: false
    status_map:
      ASSIGNED: In Progress
      FIXED: In Review
      REOPENED: In Progress

- whiteboard_tag: fxatps
  contact: tbd
  description: Privacy & Security and Anti-Tracking Team whiteboard tag
  parameters:
    jira_project_key: FXATPS

- whiteboard_tag: fxcm
  contact: 713707
  description: Firefox Credential Management Team whiteboard tag
  parameters:
    jira_project_key: FXCM
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    status_map:
      ASSIGNED: To Do
      REOPENED: To Do
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: fxdroid
  contact: 430528
  description: Firefox Android Team Tag
  parameters:
    jira_project_key: FXDROID
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_status
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Closed
      VERIFIED: Closed
      FIXED: Closed
      INVALID: Closed
      WONTFIX: Closed
      INACTIVE: Closed
      DUPLICATE: Closed
      WORKSFORME: Closed
      INCOMPLETE: Closed
      MOVED: Closed

- whiteboard_tag: fxp
  contact: tbd
  description: Performance Team
  parameters:
    jira_project_key: FXP
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      comment:
        - create_comment
    status_map:
      UNCONFIRMED: Backlog
      NEW: Backlog
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done

- whiteboard_tag: fxsync
  contact: 624105
  description: Firefox Sync Team whiteboard tag
  parameters:
    jira_project_key: SYNC

- whiteboard_tag: disco
  contact: 624105
  description: DISCO whiteboard tag
  parameters:
    jira_project_key: DISCO

- whiteboard_tag: mv3
  contact: tbd
  description: MV3 whiteboard tag
  parameters:
    jira_project_key: WEBEXT

- whiteboard_tag: nimbus
  contact: 624105
  description: Nimbus whiteboard tag
  parameters:
    jira_project_key: EXP

- whiteboard_tag: prodtest
  contact: 644672
  description: Prod testing whiteboard tag (JBI Bin Project)
  parameters:
    jira_project_key: JB

- whiteboard_tag: proton
  contact: tbd
  description: Proton whiteboard tag for Firefox Frontend
  parameters:
    jira_project_key: FIDEFE

- whiteboard_tag: relops
  contact: tbd
  description: Release Operations Team Tag
  parameters:
    jira_project_key: RELOPS

- whiteboard_tag: remote-settings
  contact: 576226
  description: Remote Settings Server issues
  parameters:
    jira_project_key: SE
    jira_components:
      - "Remote Settings"

- whiteboard_tag: snt
  contact: 696039
  description: Search/NewTab Team Tag
  parameters:
    jira_project_key: SNT

- whiteboard_tag: sp3
  contact: 396948
  description: Speedometer 3
  parameters:
    jira_project_key: SP3
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      comment:
        - create_comment
    status_map:
      UNCONFIRMED: To Do
      NEW: To Do
      ASSIGNED: In Progress
      REOPENED: In Progress
      RESOLVED: Done
      VERIFIED: Done
      FIXED: Done
      INVALID: Done
      WONTFIX: Done
      INACTIVE: Done
      DUPLICATE: Done
      WORKSFORME: Done
      INCOMPLETE: Done
      MOVED: Done
