---
# Action Config
- whiteboard_tag: addons
  contact: tbd
  description: Addons whiteboard tag for AMO Team
  enabled: true
  # module: jbi.actions.default
  parameters:
    jira_project_key: WEBEXT

- whiteboard_tag: fidedi
  contact: tbd
  description: Firefox Desktop Integration whiteboard tag
  enabled: true
  parameters:
    jira_project_key: FIDEDI

- whiteboard_tag: fidefe
  contact: gijs@mozilla.com
  description: Firefox Front End whiteboard tag
  enabled: true
  parameters:
    jira_project_key: FIDEFE
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    status_map:
      ASSIGNED: In Progress
      FIXED: Closed
      WONTFIX: Closed
      DUPLICATE: Closed
      INVALID: Closed
      INCOMPLETE: Closed
      WORKSFORME: Closed
      REOPENED: In Progress

- whiteboard_tag: flowstate
  allow_private: true
  contact: dtownsend@mozilla.com
  description: Flowstate whiteboard tag
  enabled: true
  parameters:
    jira_project_key: MR2
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue,
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    sync_whiteboard_labels: false
    status_map:
      ASSIGNED: In Progress
      FIXED: In Review
      REOPENED: In Progress

- whiteboard_tag: fxatps
  contact: tbd
  description: Privacy & Security and Anti-Tracking Team whiteboard tag
  enabled: true
  parameters:
    jira_project_key: FXATPS

- whiteboard_tag: fxcm
  contact: tbd
  description: Firefox Credential Management Team whiteboard tag
  enabled: true
  parameters:
    jira_project_key: FXCM

- whiteboard_tag: fxsync
  contact: tbd
  description: Firefox Sync Team whiteboard tag
  enabled: true
  parameters:
    jira_project_key: SYNC

- whiteboard_tag: gv
  contact: tbd
  description: GeckoView Team whiteboard tag
  enabled: true
  parameters:
    jira_project_key: ANDP

- whiteboard_tag: mv3
  contact: tbd
  description: MV3 whiteboard tag
  enabled: true
  parameters:
    jira_project_key: WEBEXT

- whiteboard_tag: nimbus
  contact: tbd
  description: Nimbus whiteboard tag
  enabled: true
  parameters:
    jira_project_key: EXP

- whiteboard_tag: prodtest
  contact: bsieber@mozilla.com
  description: Prod testing whiteboard tag (JBI Bin Project)
  enabled: true
  parameters:
    jira_project_key: JB

- whiteboard_tag: proton
  contact: tbd
  description: Proton whiteboard tag for Firefox Frontend
  enabled: true
  parameters:
    jira_project_key: FIDEFE

- whiteboard_tag: relops
  contact: tbd
  description: Release Operations Team Tag
  enabled: true
  parameters:
    jira_project_key: RELOPS

- whiteboard_tag: snt
  contact: cbellini@mozilla.com
  description: Search/NewTab Team Tag
  enabled: true
  parameters:
    jira_project_key: SNT
