---
# Action Config
- whiteboard_tag: nonprodtest
  contact: bsieber@mozilla.com
  description: Nonprod testing whiteboard tag (JBI Bin Project)
  enabled: true
  parameters:
    jira_project_key: JB

- whiteboard_tag: flowstate
  allow_private: true
  contact: dtownsend@mozilla.com
  description: Flowstate whiteboard tag
  enabled: true
  parameters:
    jira_project_key: MR2
    steps:
      new:
        - create_issue
        - maybe_delete_duplicate
        - add_link_to_bugzilla
        - add_link_to_jira
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
      existing:
        - update_issue
        - maybe_assign_jira_user
        - maybe_update_issue_resolution
        - maybe_update_issue_status
    status_map:
      ASSIGNED: In Progress
      FIXED: In Review
      REOPENED: In Progress
