name: Run lint

on: pull_request

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build lint image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: infra/Dockerfile
          push: false
          target: "lint"
          tags: ghcr.io/${{ github.repository }}-lint:${{ github.sha }}

      - name: Run lint
        run: |-
          docker run --rm \
          -e JIRA_USERNAME \
          -e JIRA_API_KEY \
          -e BUGZILLA_API_KEY \
          ghcr.io/${{ github.repository }}-lint:${{ github.sha }}
