name: Run tests

on: pull_request

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: infra/Dockerfile
          push: false
          target: "development"
          tags: ghcr.io/${{ github.repository }}-dev:${{ github.sha }}

      - name: Run tests
        run: |-
          docker run --rm \
          -e JIRA_USERNAME \
          -e JIRA_API_KEY \
          -e BUGZILLA_API_KEY \
          ghcr.io/${{ github.repository }}-dev:${{ github.sha }} \
          /app/infra/test.sh
        env:
          JIRA_USERNAME: "fake_username"
          JIRA_API_KEY: "fake_api_key"
          BUGZILLA_API_KEY: "fake_api_key"
