name: Run tests

on: pull_request

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: infra/Dockerfile
          push: false
          target: "test"
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Run tests
        run: |-
          docker run --rm \
          -e JIRA_USERNAME \
          -e JIRA_PASSWORD \
          -e BUGZILLA_API_KEY \
          ghcr.io/${{ github.repository }}:${{ github.sha }}
        env:
          JIRA_USERNAME: "fake_username"
          JIRA_PASSWORD: "fake_password"
          BUGZILLA_API_KEY: "fake_api_key"
